sudo: required
dist: trusty
services:
  - docker
language: scala
scala:
  - 2.12.6
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    # see cromwell::private::delete_sbt_boot for more info
    #- $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.coursier/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
env:
- secure: "0xgcB1CL4tnBCjaNGqIKjxuXkhpELRwK1XzruJhHWo13Z35HXS02dUgvvx4SHJlQRUCy/HfdgABwUfVtbf10XknEbKciAv+wjVW3HhdZ+MYl+WQv1UhBZXnaS56MlwFJFkPWwoRwLvyD4OssuLl6IpT3p5SoEeyPX+62kcBAvC2ybI4y8umhHth3FM2Koy3EVWCSDDd42uB1fu6os1PuRfc23slkDBcPjCPZgRaUA5x852UhLM5b0jVYDmMu8GOxzqJxMPaH7maIpSoVM1BeCPzXPgAqOT/2WGcsPFR03lsoXPr42kOlf89I1/tcHIG/0Gd/idCjM/76GYc4z+2m9HrT6RJa+iS6a8P3qNZuqUozlHLJxZNQxFXX66W8vG8N/3HbKYukPE0/Ueb0xBJPhwV+dyuFpP+YtiLA/MJ6qndLDjGjaVnixLK/j0rsteTvigKu7q+3grtuSqiEPDwWCj9Dp9DZg4H5raX85m+nKFVeGt169tS6OiUsoaGEUat2wawYWL5Q4ikEYiKKNC51qqjOlvWWXmn24yGHCV/5OJZNpQvLk4YKPs+cv0gojW8wWGonnjniSPGZ5pLKpsX1c9QZja4/dh+i1arUdMpse/lQ0XbpcullmntBupe9VYldgt8mU8fyqK/UOfViZ2YH1BRzcSk4UZe5sTBZVQQ27yw="

  matrix:
    # Setting this variable twice will cause the 'script' section to run twice with the respective env var invoked
    - >-
      BUILD_TYPE=centaurAws
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurBcs
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurEngineUpgradeLocal
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurEngineUpgradePapiV2
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurHoricromtalPapiV2
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurHoricromtalPapiV2
      BUILD_MARIADB=10.3
    - >-
      BUILD_TYPE=centaurHoricromtalEngineUpgradePapiV2
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurHoricromtalEngineUpgradePapiV2
      BUILD_MARIADB=10.3
    - >-
      BUILD_TYPE=centaurPapiUpgradePapiV1
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurPapiUpgradeNewWorkflowsPapiV1
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurLocal
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurPapiV1
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurPapiV2
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurSlurm
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurTes
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=centaurWdlUpgradeLocal
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=checkPublish
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=conformanceLocal
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=conformancePapiV2
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=conformanceTesk
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=dockerDeadlock
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=dockerScripts
      BUILD_MYSQL=5.7
    - >-
      BUILD_TYPE=sbt
      BUILD_MYSQL=5.7
      BUILD_POSTGRESQL=11.3
      BUILD_MARIADB=10.3
script:
  - src/ci/bin/test.sh
notifications:
  slack:
    rooms:
      - secure: B5KYcnhk/ujAUWlHsjzP7ROLm6MtYhaGikdYf6JYINovhMbVKnZCTlZEy7rqT3L2T5uJ25iefD500VQGk1Gn7puQ1sNq50wqjzQaj20PWEiBwoWalcV/nKBcQx1TyFT13LJv8fbFnVPxFCkC3YXoHedx8qAhDs8GH/tT5J8XOC8=
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
    on_success: change
    on_failure: change
    on_pull_requests: false
